name: Build Flatpak Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true

permissions:
  contents: write

jobs:
  build-flatpak:
    name: Build Flatpak Package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            VERSION="${GITHUB_REF##refs/*/}"
            VERSION="${VERSION#v}"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Install Flatpak and flatpak-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Install Flatpak SDK
        run: |
          sudo flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      - name: Create Flatpak manifest
        run: |
          mkdir -p flatpak
          cat > flatpak/com.github.clpi.clp-mcp.yml << 'EOF'
          app-id: com.github.clpi.clp-mcp
          runtime: org.freedesktop.Platform
          runtime-version: '23.08'
          sdk: org.freedesktop.Sdk
          command: clp-mcp
          finish-args:
            - --share=network
            - --socket=wayland
            - --socket=x11
            - --filesystem=host
          modules:
            - name: clp-mcp
              buildsystem: simple
              build-commands:
                - install -Dm755 clp-mcp /app/bin/clp-mcp
              sources:
                - type: file
                  url: https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/clp-mcp-${{ env.VERSION }}-linux-x64.tar.gz
                  sha256: PLACEHOLDER_SHA256
                  dest-filename: clp-mcp.tar.gz
                - type: shell
                  commands:
                    - tar -xzf clp-mcp.tar.gz
                    - mv clp-mcp-linux-x64 clp-mcp
          EOF

      - name: Download binary and update manifest with real SHA256
        run: |
          curl -L -o clp-mcp.tar.gz \
            https://github.com/${{ github.repository }}/releases/download/v${{ env.VERSION }}/clp-mcp-${{ env.VERSION }}-linux-x64.tar.gz
          SHA256=$(sha256sum clp-mcp.tar.gz | awk '{print $1}')
          sed -i "s/PLACEHOLDER_SHA256/$SHA256/" flatpak/com.github.clpi.clp-mcp.yml

      - name: Build Flatpak
        run: |
          flatpak-builder --force-clean --repo=repo build-dir flatpak/com.github.clpi.clp-mcp.yml

      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle repo clp-mcp-${{ env.VERSION }}.flatpak com.github.clpi.clp-mcp

      - name: Create checksum
        run: |
          sha256sum clp-mcp-${{ env.VERSION }}.flatpak > clp-mcp-${{ env.VERSION }}.flatpak.sha256

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            clp-mcp-${{ env.VERSION }}.flatpak
            clp-mcp-${{ env.VERSION }}.flatpak.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-package
          path: |
            clp-mcp-${{ env.VERSION }}.flatpak
            flatpak/

      - name: Create Flathub submission guide
        run: |
          cat > flatpak/FLATHUB_SUBMISSION.md << 'EOF'
          # Submitting to Flathub

          To submit this application to Flathub:

          1. Fork https://github.com/flathub/flathub
          2. Create a new repository under your GitHub account named `com.github.clpi.clp-mcp`
          3. Copy the manifest file `com.github.clpi.clp-mcp.yml` to the repository
          4. Create a flathub.json file:
             ```json
             {
               "only-arches": ["x86_64"]
             }
             ```
          5. Submit a pull request to https://github.com/flathub/flathub with your repository
          6. Wait for review and approval

          ## Installation from Flathub (once published)

          ```bash
          flatpak install flathub com.github.clpi.clp-mcp
          flatpak run com.github.clpi.clp-mcp
          ```

          ## Local installation

          ```bash
          flatpak install --user clp-mcp-${{ env.VERSION }}.flatpak
          flatpak run com.github.clpi.clp-mcp
          ```
          EOF
